
###
GET http://localhost:3000/api/tasks HTTP/1.1


###
GET http://localhost:3000/api/tasks?size=4 HTTP/1.1


###

POST http://localhost:3000/api/tasks HTTP/1.1
Content-Type: application/json

{
"title":"New app  con mongodb",
"description":"by bluecioladev",
"done":true


}

###

GET http://localhost:3000/api/tasks/605ebc8c84aab10ad071b453 HTTP/1.1

###

DELETE http://localhost:3000/api/tasks/605ea7453888b1379cba057f HTTP/1.1

###

GET http://localhost:3000/api/tasks/done HTTP/1.1

###

PUT http://localhost:3000/api/tasks/605ebc8c84aab10ad071b453 HTTP/1.1
Content-Type: application/json

{

    "title": "Aplication node api restfull"
}

